---
  some_fact: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          37326566636266336631613536326336653938663961643666653261343533643564666165383131
          6235663063333531376662376561653230626561643031310a643965666633333034363933633735
          64396133303739363433336238663737653438653131306334386231386131356561636531373534
          3966383231386136330a633434343565356137633537306466323561393664633739363136323236
          3532